WARNING (2023-08-02 19:08:12,748): Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE64A0>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_October.html
WARNING (2023-08-02 19:08:46,616): Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE6680>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_October.html
WARNING (2023-08-02 19:09:16,766): Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE6830>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_October.html
WARNING (2023-08-02 19:09:56,873): Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE69B0>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_October.html
WARNING (2023-08-02 19:10:45,014): Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE6B30>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_October.html
CRITICAL (2023-08-02 19:11:11,765): <class 'requests.exceptions.ConnectTimeout'>
HTTPSConnectionPool(host='earthquake.phivolcs.dost.gov.ph', port=443): Max retries exceeded with url: /EQLatest-Monthly/2018/2018_October.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020794DE6CB0>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)'))
['  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\phivolcs_bulletin.py", line 130, in <module>\n    df_phv = get_page(sys.argv[1])\n', '  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\phivolcs_bulletin.py", line 32, in get_page\n    page_request = requests_retry(page_url, verify_ssl=False)\n', '  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\utils\\requests_retry.py", line 27, in requests_retry\n    page_request = s.get(url, verify=verify_ssl, headers=headers)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\adapters.py", line 553, in send\n    raise ConnectTimeout(e, request=request)\n']
