WARNING (2023-08-02 18:33:39,696): Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F28F0>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_November.html
WARNING (2023-08-02 18:34:13,759): Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F2AD0>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_November.html
WARNING (2023-08-02 18:34:49,836): Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F2C80>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_November.html
WARNING (2023-08-02 18:35:24,713): Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F2E00>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_November.html
WARNING (2023-08-02 18:36:12,836): Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F2F80>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)')': /EQLatest-Monthly/2018/2018_November.html
CRITICAL (2023-08-02 18:36:44,947): <class 'requests.exceptions.ConnectTimeout'>
HTTPSConnectionPool(host='earthquake.phivolcs.dost.gov.ph', port=443): Max retries exceeded with url: /EQLatest-Monthly/2018/2018_November.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000151DE1F3100>, 'Connection to earthquake.phivolcs.dost.gov.ph timed out. (connect timeout=None)'))
['  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\phivolcs_bulletin.py", line 130, in <module>\n    df_phv = get_page(sys.argv[1])\n', '  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\phivolcs_bulletin.py", line 32, in get_page\n    page_request = requests_retry(page_url, verify_ssl=False)\n', '  File "C:\\Users\\AMH-L91\\documents\\projects\\phivolcs-bulletins\\utils\\requests_retry.py", line 27, in requests_retry\n    page_request = s.get(url, verify=verify_ssl, headers=headers)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\AMH-L91\\anaconda3\\envs\\webparse\\lib\\site-packages\\requests\\adapters.py", line 553, in send\n    raise ConnectTimeout(e, request=request)\n']
